### ISSUE TITLE
Unserialize incorrectly serialized 2 byte Unicode characters

### ISSUE THREAD

**Issue by OscarMelin** [CheffleSE/php-serialize#2]
The gem is unable to parse strings in arrays that have used bytesize when defining string lengths.

`PHP.unserialize('s:6:"hallå";')` works
`PHP.unserialize('a:2:{i:0;s:6:"hallå";i:1;s:4:"test";}')` fails

**Comment by OscarMelin** [comment]
@loveo :slightly_smiling_face:

**Comment by loveo** [comment]
Så WP kommer ibland spara ner `'s:14:"Operakällaren"'` och ibland `'s:13:"Operakällaren"'` ? @OscarMelin 

Fick förut `s:145:"Bartenderutbildningen nov. 2009 kompletterades under 2010 och 2011 med BarAkademins Barista-, serverings- och vinkurs samt Ölsommelierutbildning."` (145 tecken lång men 146 bytesize). När skrivs dessa?

**Comment by loveo** [comment]
https://github.com/CheffleSE/php-serialize/pull/3 should solve this
